### ISSUE TITLE
Unable to use PasteImage on wayland

### ISSUE THREAD

**Issue by ghost** [elentok/open-link.nvim#1]
Hi! I can't use PasteImage on wayland as it requires xclip, and I can't find where I can change that to wl-paste

**Comment by elentok** [comment]
Hi @BestInfinity 

I just merged a commit that adds Wayland support (I recently switched to Ubuntu 23.10 on one of my machine so I managed to test it.

Thanks for the tip :pray: 

Let me know if it works for you :+1:

**Comment by BestInfinity** [comment]
Just tried it I'm guessing i need to add some sub command or something to make it know I need wl-paste, but i'm kinda new to neovim so i don't really know how can i check which? (just running it normally prints same error of no xclip)

**Comment by BestInfinity** [comment]
Wait never mind, an unrelated crash of my window manager made it use wl-paste now
